# Macro file for the initialization of example G4BL2
# in interactive session
#
# Set some default verbose
#
/control/verbose 2
/control/saveHistory
/run/verbose 2
#
# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 4
#

# Add Geometry

/Geometry/add BeamLine
/Geometry/add TargetChamberO17
/Geometry/add TargetHolder

/Geometry/add BGODetector

/Geometry/add LeadShielding
/Geometry/LeadShielding/setup BGO

# Initialize kernel
/run/initialize

# Set output file name
/run/setFileName prova.root

# Select Primary Generator (NuclideGun)
/PrimaryGenerator/select NuclideGun
/PrimaryGenerator/NuclideGun/mass 15
/PrimaryGenerator/NuclideGun/charge 8
/PrimaryGenerator/NuclideGun/position 0 0 3.4990 mm

# Visualization setting
/control/execute mac/vis_wrl.mac
